---
trigger:
  branches:
    include:
    - main

variables:
  vmImage: ubuntu-latest
  azureServiceConnection: AdoServiceConnection

pool:
  vmImage: $(vmImage)

steps:
- task: TerraformInstaller@0
  displayName: 'TF install'
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  displayName: 'TF version print'
  inputs:
    command: 'version'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: 'TF init'
  inputs:
    command: 'init'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: 'TF validate'
  inputs:
    command: 'validate'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: 'TF plan'
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)\Azure\_Simple'
#    allowTelemetryCollection: true
#    publishPlanResults: 'sandbox'

