---
  trigger:
    branches:
      include:
      - main
  
  variables:
    vmImage: ubuntu-latest
    azureServiceConnection: AdoServiceConnection
  
  pool:
    vmImage: $(vmImage)
  
  steps:
  - task: CmdLine@2
    displayName: 'Moving to proper dir'
    inputs:
      script: |
        echo "Print default workdir:"
        echo  '$(System.DefaultWorkingDirectory)'
        echo "Going to: $(System.DefaultWorkingDirectory)/Azure/Azure-Sandbox/3a-pipeline"
        cd $(System.DefaultWorkingDirectory)/Azure/Azure-Sandbox/3a-pipeline
        echo "Print PWD:"
        pwd

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'AdoServiceConnection'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az account show --subscription 8dac1cb1-7130-4137-a400-92c8b6c10bd9


  - task: TerraformInstaller@0
    displayName: 'TF install'
    inputs:
      terraformVersion: 'latest'
  
  - task: TerraformCLI@1
    displayName: 'TF version print'
    inputs:
      command: 'version'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Azure/Azure-Sandbox/3a-pipeline'
      allowTelemetryCollection: true
  
  - task: TerraformCLI@1
    displayName: 'TF init'
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Azure/Azure-Sandbox/3a-pipeline'
      allowTelemetryCollection: true
  
  - task: TerraformCLI@1
    displayName: 'TF validate'
    inputs:
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Azure/Azure-Sandbox/3a-pipeline'
      allowTelemetryCollection: true
  
  - task: TerraformCLI@1
    displayName: 'TF plan'
    inputs:
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Azure/Azure-Sandbox/3a-pipeline'
  #    allowTelemetryCollection: true
  #    publishPlanResults: 'sandbox'
  
  