---
  trigger:
    branches:
      include:
      - main
  
  variables:
    vmImage: ubuntu-latest
    azureServiceConnection: AdoServiceConnection
  
  pool:
    vmImage: $(vmImage)
  
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'AdoServiceConnection'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az account show --subscription '63abcf25-b8df-4c76-8b31-5004c9ba37cd'

  - task: TerraformInstaller@0
    displayName: 'TF install'
    inputs:
      terraformVersion: 'latest'
    
  - task: AzureCLI@2
    displayName: 'TF init'
    inputs:
      azureSubscription: 'AdoServiceConnection'
      scriptType: bash
      workingDirectory: '$(System.DefaultWorkingDirectory)/Azure/Azure-Sandbox/3a-pipeline'
      scriptLocation: inlineScript
      inlineScript: |
        terraform init

  - task: AzureCLI@2
    displayName: 'TF validate'
    inputs:
      azureSubscription: 'AdoServiceConnection'
      scriptType: bash
      workingDirectory: '$(System.DefaultWorkingDirectory)/Azure/Azure-Sandbox/3a-pipeline'
      scriptLocation: inlineScript
      inlineScript: |
        terraform validate

  - task: AzureCLI@2
    displayName: 'TF plan'
    inputs:
      azureSubscription: 'AdoServiceConnection'
      scriptType: bash
      workingDirectory: '$(System.DefaultWorkingDirectory)/Azure/Azure-Sandbox/3a-pipeline'
      scriptLocation: inlineScript
      inlineScript: |
        terraform plan

  - task: AzureCLI@2
    displayName: 'TF apply'
    inputs:
      azureSubscription: 'AdoServiceConnection'
      scriptType: bash
      workingDirectory: '$(System.DefaultWorkingDirectory)/Azure/Azure-Sandbox/3a-pipeline'
      scriptLocation: inlineScript
      inlineScript: |
        terraform apply --auto-approve