---
  trigger:
    branches:
      include:
      - main
  
  variables:
    vmImage: ubuntu-latest
    azureServiceConnection: AdoServiceConnection
  
  pool:
    vmImage: $(vmImage)
  
  steps:
  - task: CmdLine@2
    displayName: 'Moving to proper dir'
    inputs:
      script: |
        echo "Print default workdir:"
        echo  '$(System.DefaultWorkingDirectory)'
        echo "Going to: $(System.DefaultWorkingDirectory)\Azure\Azure-Sandbox\3a-pipeline"
        cd $(System.DefaultWorkingDirectory)\Azure\Azure-Sandbox\3a-pipeline
        echo "Print PWD:"
        pwd
  - task: TerraformInstaller@0
    displayName: 'TF install'
    inputs:
      terraformVersion: 'latest'
  
  - task: TerraformCLI@1
    displayName: 'TF version print'
    inputs:
      command: 'version'
      allowTelemetryCollection: true
  
  - task: TerraformCLI@1
    displayName: 'TF init'
    inputs:
      command: 'init'
      allowTelemetryCollection: true
  
  - task: TerraformCLI@1
    displayName: 'TF validate'
    inputs:
      command: 'validate'
      allowTelemetryCollection: true
  
  - task: TerraformCLI@1
    displayName: 'TF plan'
    inputs:
      command: 'plan'
  #    allowTelemetryCollection: true
  #    publishPlanResults: 'sandbox'
  
  